---
# The 'accessibility: yes' flag is a placeholder and does nothing
- hosts: local
  name: 'Install ControlPlane 1.6.7 App'
  become: no
  gather_facts: no
  vars:
    app_name: 'https://github.com/dustinrue/ControlPlane/releases/download/1.6.7/ControlPlane-1.6.7.dmg'
    installer_type: app
    download_filetype: dmg
    install_method: dmg
    add_to_dock: no
    accessibility: no
  roles:
    - init
    - install
    - cleanup
