---
- hosts: local
  name: Install Docker for Mac
  become: no
  gather_facts: no
  vars:
    app_name: Docker
    app_url: 'https://download.docker.com/mac/stable/Docker.dmg'
    installer_type: app
    download_filetype: dmg
    install_method: dmg
    add_to_dock: yes
  roles:
    - init
    - install
    - cleanup
