---
- hosts: local
  name: Install Meld App
  become: no
  gather_facts: no
  vars:
    app_name: Meld
    app_url: 'https://github.com/yousseb/meld/releases/download/osx-14/meldmerge.dmg'
    installer_type: app
    download_filetype: dmg
    install_method: dmg
  roles:
    - init
    - install
    - cleanup
