---
- hosts: local
  name: Install Slack App
  become: no
  gather_facts: no
  vars:
    app_name: Slack
    app_url: 'https://slack.com/ssb/download-osx'
    installer_type: app
    download_filetype: dmg
    install_method: dmg
    add_to_dock: yes
  roles: 
    - init
    - install
    - cleanup
