---
# Synergy needs to be added to the accessibility list.
# The 'accessibility: yes' flag is a placeholder and does nothing
- hosts: local
  name: Install Synergy 1.8.8 App
  become: no
  gather_facts: no
  vars:
    app_name: Synergy
    app_url: 'https://ayera.dl.sourceforge.net/project/synergy-stable-builds/v1.8.8-stable/synergy-v1.8.8-stable-MacOSX-x86_64.dmg'
    installer_type: app
    download_filetype: dmg
    install_method: dmg
    add_to_dock: no
    accessibility: yes
  roles:
    - init
    - install
    - cleanup
