---

- name: Install Hashicorp Vagrant
  hosts: localhost
  become: yes
  gather_facts: no
  vars:
    app_name: Vagrant
    app_url: https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.dmg
    installer_type: pkg
    install_method: dmg
    download_filetype: dmg
    add_to_dock: no
  roles:
    - init
    - install
    - cleanup
