---
- hosts: local
  name: Install Microsoft Visual Studio Code
  become: no
  gather_facts: no
  vars:
    app_name: Visual Studio Code
    app_url: https://go.microsoft.com/fwlink/?LinkID=620882
    installer_type: app
    install_method: dmg
    download_filetype: zip
    add_to_dock: yes
  roles:
    - init
    - install
    - cleanup
