---

##
## copy app to /applications
## I use the argv: form since it ensures proper argument passing if the app has spaces in the name
##

- name: 'Copy {{ install_src }}/{{ app_name }} to {{ install_dest }} directory'
  command:
    argv:
      - 'cp'
      - '-R'
      - '{{ install_src }}/{{ app_name }}'
      - '{{ install_dest }}'
