---

## put the app into the dock

- name: Adding {{ app_name }} to the dock
  register: dock_write
  command: 
    argv:
    - defaults 
    - write 
    - com.apple.dock
    - persistent-apps 
    - -array-add 
    - 
      <dict>
      <key>tile-data</key>
      <dict>
      <key>file-data</key>
      <dict>
      <key>_CFURLString</key>
      <string>/Applications/{{ app_name }}.app</string>
      <key>_CFURLStringType</key>
      <integer>0</integer>
      </dict>
      </dict>
      </dict>

- name: 'Resarting the Dock'
  command: 'killall Dock'
